name: cultyvate
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.3.7+48

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

#  flutter_localizations:
#    sdk: flutter
  flutter_screenutil:
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.15
  cupertino_battery_indicator:
  signal_strength_indicator:
  flutter_localization: ^0.1.1
  i18n_extension_importer: ^0.0.6
  firebase_core_platform_interface: 4.5.1
  get: ^4.6.5
  font_awesome_flutter: ^10.1.0
  charts_flutter: ^0.12.0
  flutter_advanced_calendar: ^1.1.5
  permission_handler: ^10.4.3
  flutter_secure_storage: ^5.0.3
  json_annotation: ^4.8.1
  sqflite:
  dio: ^4.0.6
  fluttertoast: ^8.0.9
  google_fonts:
  i18n: ^4.1.0
  i18n_extension: ^4.0.0
  localization: ^2.1.0
  shared_preferences: ^2.0.15
  flutter_dotenv: ^5.0.2
  url_launcher:
  flutter_spinkit: ^5.1.0
  fl_chart: ^0.55.1
  firebase_messaging: ^12.0.2
  flutter_local_notifications: ^9.7.0
  syncfusion_flutter_charts: ^20.3.56
  webview_flutter: ^3.0.4
  package_info_plus:
  flutter_svg: ^1.1.6
  internet_check: ^0.0.2
  flutter_native_timezone:
  time_machine: ^0.9.17
  equatable: ^2.0.5
  gif: ^2.3.0
  flutter_bloc: ^7.0.0
  gif_view: ^0.4.0
  bloc:
  hexcolor: any
  syncfusion_flutter_gauges: any

dependency_overrides:
  intl: ^0.18.0
dev_dependencies:
  build_runner: ^2.4.7
  json_serializable: ^6.1.1
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/fonts/lato/
    - assets/locales/
    - packages/time_machine/data/cultures/cultures.bin
    - packages/time_machine/data/tzdb/tzdb.bin
